#ifndef TOPK_SINGLEPASS_DETAIL_DEFINITIONS_MINIMAL_HPP_
#define TOPK_SINGLEPASS_DETAIL_DEFINITIONS_MINIMAL_HPP_

#define TOPK_SINGLEPASS_BITS_BATCH_SIZES 1, 7, 16
#define TOPK_SINGLEPASS_BITS_BLOCK_SIZES 128

#define TOPK_SINGLEPASS_FC_DIM_REGS 2
#define TOPK_SINGLEPASS_FC_DIM_MULTS 2
#define TOPK_SINGLEPASS_FC_QUERY_REGS 8
#define TOPK_SINGLEPASS_FC_DB_REGS 4
#define TOPK_SINGLEPASS_FC_BLOCK_QUERY_DIMS 4

#endif // TOPK_SINGLEPASS_DETAIL_DEFINITIONS_MINIMAL_HPP_
