#ifndef TOPK_SINGLEPASS_DETAIL_DEFINITIONS_APPLICATION_HPP_
#define TOPK_SINGLEPASS_DETAIL_DEFINITIONS_APPLICATION_HPP_

// Supported application configurations. The full kNN build includes batches 1 to 16.
#define TOPK_SINGLEPASS_BITS_BATCH_SIZES 1, 4, 7, 16
#define TOPK_SINGLEPASS_BITS_BLOCK_SIZES 128, 256, 512

#endif // TOPK_SINGLEPASS_DETAIL_DEFINITIONS_APPLICATION_HPP_
