#ifndef TOPK_SINGLEPASS_DEFINITIONS_ALL_HPP_
#define TOPK_SINGLEPASS_DEFINITIONS_ALL_HPP_

#define TOPK_SINGLEPASS_BITS_BATCH_SIZES 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
#define TOPK_SINGLEPASS_BITS_BLOCK_SIZES 128, 256, 512

#define TOPK_SINGLEPASS_FC_DIM_REGS 1, 2, 4
#define TOPK_SINGLEPASS_FC_DIM_MULTS 1, 2, 4
#define TOPK_SINGLEPASS_FC_QUERY_REGS 2, 4, 8, 16
#define TOPK_SINGLEPASS_FC_DB_REGS 4, 8, 16
#define TOPK_SINGLEPASS_FC_BLOCK_QUERY_DIMS 1, 2, 4

#endif // TOPK_SINGLEPASS_DEFINITIONS_ALL_HPP_
